import os
from lxml import etree


TEI_NS = "http://www.tei-c.org/ns/1.0"
XML_NS = "http://www.w3.org/XML/1998/namespace"
NSMAP = {None: TEI_NS}


def generate_tei_xml(
    text: str,
    metadata: dict,
    output_path: str,
) -> str:
    """
    Generate TEI-XML conforming to archival standards.

    Args:
        text: Transcribed text (newlines = line breaks)
        metadata: Dict with keys like "title", "engine_used", "confidence", "source"
        output_path: Where to write the XML file

    Returns path to output XML.
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    tei = etree.Element("TEI", nsmap=NSMAP)

    # Header
    header = etree.SubElement(tei, "teiHeader")
    file_desc = etree.SubElement(header, "fileDesc")

    title_stmt = etree.SubElement(file_desc, "titleStmt")
    title = etree.SubElement(title_stmt, "title")
    title.text = metadata.get("title", "OCR Transcription")

    source_desc = etree.SubElement(file_desc, "sourceDesc")

    p1 = etree.SubElement(source_desc, "p")
    p1.text = "OCR transcription generated by Historical Document Pipeline"

    engine = metadata.get("engine_used", "unknown")
    confidence = metadata.get("confidence", 0.0)
    p2 = etree.SubElement(source_desc, "p")
    p2.text = f"Engine: {engine}, Confidence: {confidence:.2%}"

    if "source" in metadata:
        p3 = etree.SubElement(source_desc, "p")
        p3.text = f"Source: {metadata['source']}"

    # Body
    text_elem = etree.SubElement(tei, "text")
    body = etree.SubElement(text_elem, "body")
    div = etree.SubElement(body, "div")

    regions = metadata.get("regions")
    if isinstance(regions, list) and regions:
        facsimile = etree.SubElement(tei, "facsimile")
        surface = etree.SubElement(
            facsimile,
            "surface",
            attrib={f"{{{XML_NS}}}id": "page_1", "n": "1"},
        )
        if "image_width" in metadata and "image_height" in metadata:
            surface.set("lrx", str(int(metadata["image_width"])))
            surface.set("lry", str(int(metadata["image_height"])))

        p = etree.SubElement(div, "p")
        line_refs = []
        for region in regions:
            bbox = region.get("bbox") if isinstance(region, dict) else None
            if not isinstance(bbox, dict):
                continue

            line_index = int(region.get("line_index", len(line_refs)))
            line_id = f"line_{line_index}"

            x = int(bbox.get("x", 0))
            y = int(bbox.get("y", 0))
            w = int(bbox.get("w", 0))
            h = int(bbox.get("h", 0))

            etree.SubElement(
                surface,
                "zone",
                attrib={
                    f"{{{XML_NS}}}id": line_id,
                    "type": "line",
                    "ulx": str(x),
                    "uly": str(y),
                    "lrx": str(x + w),
                    "lry": str(y + h),
                },
            )

            line_elem = etree.SubElement(
                p,
                "l",
                attrib={"corresp": f"#{line_id}", "n": str(line_index)},
            )
            line_elem.text = str(region.get("text", ""))
            line_refs.append(line_id)

        if not line_refs:
            lines = text.split("\n") if text else [""]
            p = etree.SubElement(div, "p")
            for i, line in enumerate(lines):
                if i > 0:
                    etree.SubElement(p, "lb")
                if i == 0:
                    p.text = line
                else:
                    lb_elements = p.findall("lb")
                    if lb_elements:
                        lb_elements[-1].tail = line
    else:
        lines = text.split("\n") if text else [""]
        p = etree.SubElement(div, "p")

        for i, line in enumerate(lines):
            if i > 0:
                etree.SubElement(p, "lb")
            if i == 0:
                p.text = line
            else:
                lb_elements = p.findall("lb")
                if lb_elements:
                    lb_elements[-1].tail = line

    # Write
    tree = etree.ElementTree(tei)
    tree.write(
        output_path,
        xml_declaration=True,
        encoding="UTF-8",
        pretty_print=True,
    )

    return output_path
