import os
from lxml import etree


TEI_NS = "http://www.tei-c.org/ns/1.0"
NSMAP = {None: TEI_NS}


def generate_tei_xml(
    text: str,
    metadata: dict,
    output_path: str,
) -> str:
    """
    Generate TEI-XML conforming to archival standards.

    Args:
        text: Transcribed text (newlines = line breaks)
        metadata: Dict with keys like "title", "engine_used", "confidence", "source"
        output_path: Where to write the XML file

    Returns path to output XML.
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    tei = etree.Element("TEI", nsmap=NSMAP)

    # Header
    header = etree.SubElement(tei, "teiHeader")
    file_desc = etree.SubElement(header, "fileDesc")

    title_stmt = etree.SubElement(file_desc, "titleStmt")
    title = etree.SubElement(title_stmt, "title")
    title.text = metadata.get("title", "OCR Transcription")

    source_desc = etree.SubElement(file_desc, "sourceDesc")

    p1 = etree.SubElement(source_desc, "p")
    p1.text = "OCR transcription generated by Historical Document Pipeline"

    engine = metadata.get("engine_used", "unknown")
    confidence = metadata.get("confidence", 0.0)
    p2 = etree.SubElement(source_desc, "p")
    p2.text = f"Engine: {engine}, Confidence: {confidence:.2%}"

    if "source" in metadata:
        p3 = etree.SubElement(source_desc, "p")
        p3.text = f"Source: {metadata['source']}"

    # Body
    text_elem = etree.SubElement(tei, "text")
    body = etree.SubElement(text_elem, "body")
    div = etree.SubElement(body, "div")

    # Split text into lines
    lines = text.split("\n") if text else [""]
    p = etree.SubElement(div, "p")

    for i, line in enumerate(lines):
        if i > 0:
            etree.SubElement(p, "lb")
        # Add text content
        if i == 0:
            p.text = line
        else:
            # Text after <lb/> goes in tail
            lb_elements = p.findall("lb")
            if lb_elements:
                lb_elements[-1].tail = line

    # Write
    tree = etree.ElementTree(tei)
    tree.write(
        output_path,
        xml_declaration=True,
        encoding="UTF-8",
        pretty_print=True,
    )

    return output_path
